name: Build on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build project inside container
        run: |
          git config --file .gitmodules submodule.vendor/wayland-odin.url https://github.com/jqcorreia/wayland-odin.git
          git submodule sync
          git submodule update --init --recursive

          ls -l .
          echo "========================"
          echo ${{ github.workspace }}

          docker run --rm \
            -v ${{ github.workspace }}:/project \
            -w /project \
            ghcr.io/jqcorreia/super-build:latest \
            ci/ci_build.sh 

          pwd
          ls -l ./project

          # tar -czf super.tar.gz super
