name: Build on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build project inside container
        run: |
          git config --file .gitmodules submodule.vendor/wayland-odin.url https://github.com/jqcorreia/wayland-odin.git
          git config --file .gitmodules submodule.vendor/libschrift-odin.url https://github.com/jqcorreia/libschrift-odin.git
          git submodule sync
          git submodule update --init --recursive

          docker run --rm \
            -v ${{ github.workspace }}:/code \
            -w /code \
            ghcr.io/jqcorreia/super-build:latest \
            ci/ci_build.sh 

          tar -czf super.tar.gz build/super

      - name: Upload tar.gz as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-archive
          path: super.tar.gz
